DjangoConsulting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('accounts/', include('accounts.urls')),
                  path("ckeditor5/", include('django_ckeditor_5.urls')),

                  path("candidates/", include("candidates.urls", namespace="candidates")),
                  path('documents/', include('manage_documents.urls')),
                  path('jobs/', include('jobs.urls', namespace='jobs')),

              ]

candidates/urls.py
# candidates/urls.py
from django.urls import path
from . import views


app_name = "candidates"

urlpatterns = [
    # Candidate URLs

    path("search/", views.candidate_search_view, name="candidate_search"),

    path("", views.candidate_list, name="candidate_list"),
    path("create/", views.candidate_create, name="candidate_create"),
    path("<int:pk>/", views.candidate_detail, name="candidate_detail"),
    path("<int:pk>/update/", views.candidate_update, name="candidate_update"),
    path("<int:pk>/delete/", views.candidate_delete, name="candidate_delete"),
    # File Deletion URLs
    path(
        "<int:candidate_pk>/delete_resume/", views.delete_resume, name="delete_resume"
    ),
    path(
        "<int:candidate_pk>/delete_personal_image/",
        views.delete_personal_image,
        name="delete_personal_image",
    ),
    path(
        "<int:candidate_pk>/delete_id_copy/",
        views.delete_id_copy,
        name="delete_id_copy",
    ),
    path(
        "<int:candidate_pk>/delete_passport_copy/",
        views.delete_passport_copy,
        name="delete_passport_copy",
    ),
    # Education URLs
    path(
        "<int:candidate_pk>/educations/create/",
        views.education_create,
        name="education_create",
    ),
    path(
        "educations/<int:pk>/update/", views.education_update, name="education_update"
    ),
    path(
        "educations/<int:pk>/delete/", views.education_delete, name="education_delete"
    ),
    # Education File Deletion
    path(
        "educations/<int:education_pk>/delete_certification/",
        views.delete_education_certification,
        name="delete_education_certification",
    ),
    path(
        "educations/<int:education_pk>/delete_transcript/",
        views.delete_education_transcript,
        name="delete_education_transcript",
    ),
    # Experience URLs
    path(
        "<int:candidate_pk>/experiences/create/",
        views.experience_create,
        name="experience_create",
    ),
    path(
        "experiences/<int:pk>/update/",
        views.experience_update,
        name="experience_update",
    ),
    path(
        "experiences/<int:pk>/delete/",
        views.experience_delete,
        name="experience_delete",
    ),
    # Experience File Deletion
    path(
        "experiences/<int:experience_pk>/delete_certification/",
        views.delete_experience_certification,
        name="delete_experience_certification",
    ),
    # Language URLs
    path(
        "languages/<int:candidate_pk>/languages/create/",
        views.language_create,
        name="language_create",
    ),
    path("languages/<int:pk>/delete/", views.language_delete, name="language_delete"),
    # Training Course URLs
    path(
        "<int:candidate_pk>/training_courses/create/",
        views.training_course_create,
        name="training_course_create",
    ),
    path(
        "training_courses/<int:pk>/update/",
        views.training_course_update,
        name="training_course_update",
    ),
    path(
        "training_courses/<int:pk>/delete/",
        views.training_course_delete,
        name="training_course_delete",
    ),
    # Training Course File Deletion
    path(
        "<int:training_course_pk>/delete_certification/",
        views.delete_training_course_certification,
        name="delete_training_course_certification",
    ),
    # License URLs
    path(
        "<int:candidate_pk>/licenses/create/",
        views.license_create,
        name="license_create",
    ),
    path("licenses/<int:pk>/update/", views.license_update, name="license_update"),
    path("licenses/<int:pk>/delete/", views.license_delete, name="license_delete"),
    # License File Deletion
    path(
        "<int:license_pk>/delete_license_copy/",
        views.delete_license_copy,
        name="delete_license_copy",
    ),
    # Candidate Application Data URLs
    path(
        "<int:candidate_pk>/application_data/update/",
        views.candidate_application_data_update,
        name="candidate_application_data_update",
    ),
    path(
        "<int:candidate_pk>/application_data/detail/",
        views.candidate_application_data_detail,
        name="candidate_application_data_detail",
    ),
    path(
        "candidate/<int:candidate_id>/delete_blood_test_report/",
        views.delete_blood_test_report,
        name="delete_blood_test_report",
    ),
    path(
        "candidate/<int:candidate_id>/delete_xray_test_report/",
        views.delete_xray_test_report,
        name="delete_xray_test_report",
    ),
    path(
        "candidate/<int:candidate_id>/delete_fit_to_work_report/",
        views.delete_fit_to_work_report,
        name="delete_fit_to_work_report",
    ),
    # DataFlow_certificate_copy
    path(
        "candidate/<int:candidate_id>/delete_dataflow_certificate/",
        views.delete_dataflow_certificate,
        name="delete_dataflow_certificate_copy",
    ),
    path(
        "candidate/<int:candidate_id>/delete_pregnancy_report/",
        views.delete_pregnancy_report,
        name="delete_pregnancy_report",
    ),
    path(
        "candidate/<int:candidate_id>/delete_dhp_certificate/",
        views.delete_dhp_certificate,
        name="delete_dhp_certificate",
    ),
    path(
        "candidate/<int:candidate_id>/delete_prometric_certificate/",
        views.delete_prometric_certificate,
        name="delete_prometric_certificate",
    ),
# delete_prometric_appointment
    path(
        "candidate/<int:candidate_id>/delete_prometric_appointment_copy/",
        views.delete_prometric_appointment_copy,
        name="delete_prometric_appointment_copy",
    ),
    # delete_police_clearance_copy
    path(
        "candidate/<int:candidate_id>/delete_police_clearance_copy/",
        views.delete_police_clearance_copy,
        name="delete_police_clearance_copy",
    ),
    # delete_visa_copy
    path(
        "candidate/<int:candidate_id>/delete_visa_copy/",
        views.delete_visa_copy,
        name="delete_visa_copy",
    ),
    path(

        "candidate/<int:candidate_id>/delete_police_clearance_copy/",
        views.delete_police_clearance_copy,
        name="delete_police_clearance_copy",
    ),
    path(
        "candidate/<int:candidate_id>/delete_visa_copy/",
        views.delete_visa_copy,
        name="delete_visa_copy",
    ),

    path('download/', views.download_file, name='download_file'),

    path('download-directory/<int:candidate_id>/', views.download_candidate_directory,
         name='download_candidate_directory'),
    path('download-vcf/<int:candidate_id>/', views.download_vcf, name='download_vcf'),

]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_opportunity_list, name='job_opportunity_list'),
    path('job-opportunities/', views.job_opportunity_list, name='job_opportunity_list'),
    path('job-opportunities/add/', views.job_opportunity_create, name='job_opportunity_create'),
    path('job-opportunities/<int:pk>/', views.job_opportunity_detail, name='job_opportunity_detail'),
    path('job-opportunities/<int:pk>/edit/', views.job_opportunity_edit, name='job_opportunity_edit'),
    path('job-opportunities/<int:pk>/candidates/', views.job_opportunity_candidates, name='job_opportunity_candidates'),
    # This endpoint is not used in the provided code. If you want to include it, you can uncomment it and modify the view function accordingly.
    path('job-opportunities/<int:pk>/compatible-candidates/', views.job_opportunity_compatible_candidates, name='job_opportunity_compatible_candidates'),
    path('job-opportunities/<int:job_id>/add-candidate/<int:candidate_id>/', views.job_opportunity_add_candidate, name='job_opportunity_add_candidate'),
    path('job-opportunities/<int:job_id>/remove-candidate/<int:candidate_id>/', views.job_opportunity_remove_candidate, name='job_opportunity_remove_candidate'),
]

jobs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from utilities.models import (
    Nationality,
    DegreeChoices,
    FieldOfStudy,
    Department,
)

from candidates.models import Candidate

class JobOpportunity(models.Model):
    job_title = models.CharField(max_length=255, verbose_name=_("Job Title"))
    job_description = models.TextField(verbose_name=_("Job Description"))
    job_department = models.ForeignKey(
        Department,
        on_delete=models.PROTECT,
        verbose_name=_("Job Department"),
        related_name='job_opportunities_as_department',  # Added related_name
    )
    company_name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Enter the name of the company."),
        verbose_name=_("Company Name"),
    )
    minimum_years_of_experience = models.PositiveIntegerField(
        verbose_name=_("Minimum Years of Experience")
    )
    accepted_degrees = models.ManyToManyField(
        DegreeChoices,
        verbose_name=_("Accepted Degrees"),
    )
    fields_of_study = models.ManyToManyField(
        FieldOfStudy,
        verbose_name=_("Fields of Study"),
    )
    nationalities = models.ManyToManyField(
        Nationality,
        verbose_name=_("Nationalities"),
    )
    minimum_age = models.PositiveIntegerField(verbose_name=_("Minimum Age"))
    maximum_age = models.PositiveIntegerField(verbose_name=_("Maximum Age"))
    gender = models.CharField(
        choices=[("M", _("Male")), ("F", _("Female")), ("Any", _("Any"))],
        max_length=3,
        verbose_name=_("Gender"),
    )
    departments = models.ManyToManyField(
        Department,
        verbose_name=_("Required Experience Departments"),
        help_text=_("Select departments that the candidate should have experience in."),
        related_name='job_opportunities_as_required',  # Added related_name
    )
    candidates = models.ManyToManyField(
        Candidate,
        related_name='job_opportunities',
        blank=True,
        verbose_name=_("Candidates"),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    class Meta:
        verbose_name = _("Job Opportunity")
        verbose_name_plural = _("Job Opportunities")
        ordering = ["-created_at"]

    def __str__(self):
        return self.job_title

candidates/templates/candidates/candidate_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h2>Confirm Deletion</h2>
    <p>Are you sure you want to delete {{ candidate.full_name }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

candidates/templates/candidates/candidate_form.html
{% extends 'base.html' %}
{% load document_preview %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}



    <h2>{{ object.pk|yesno:"Edit Profile,Create Profile" }}</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}

       <h5 class="mb-3">Personal Details</h5>
            <hr>
        <div class="row mb-3">

            <div class="col-md-3">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.second_name|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.third_name|as_crispy_field }}
            </div>
            <div class="col-md-3">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>


        <div class="row mb-3">

            <div class="col-md-6">
                {{ form.gender|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.birthday|as_crispy_field }}
            </div>


        </div>


        <div class="row mb-3">

            <div class="col-md-6">
                {{ form.country|as_crispy_field }}
            </div>

            <div class="col-md-6">
                {{ form.address|as_crispy_field }}
            </div>

        </div>

   <h5 class="mb-3">Contact Details</h5>
        <hr>
        <div class="row mb-3">

            <div class="col-md-4">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.call_phone_number|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.whatsapp_phone_number|as_crispy_field }}
            </div>
        </div>

     <h5 class="mb-3">Identity information.</h5>
        <hr>
        <div class="row mb-3">

            <div class="col-md-4">
                {{ form.nationality|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.national_id_number|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {% if candidate.national_id_copy and candidate.national_id_copy.url %}
                    <strong class="mb-3">National ID Copy</strong>
                    {% document_preview candidate.national_id_copy.url %}
                    <!-- Example delete link with class for JavaScript selection -->
                    <a href="#" class="delete-file-link" data-url="{% url 'candidates:delete_id_copy' candidate.id %}"
                       data-file-name="National ID Copy">
                        <i class="fa fa-trash"></i> delete
                    </a>


                {% else %}
                    {{ form.national_id_copy|as_crispy_field }}
                {% endif %}
            </div>
        </div>
        <!-- 'passport_copy', 'passport_expiration_date', 'passport_id', -->
     <h5 class="mb-3"> Please upload a copy of your passport</h5>
        <hr>
        <div class="row mb-3">

            <div class="col-md-4">
                {{ form.passport_id|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.passport_expiration_date|as_crispy_field }}
            </div>
            <div class="col-md-4">

                {% if candidate.passport_copy and candidate.passport_copy.url %}
                    <strong class="mb-3">Passport Copy</strong>
                    {% document_preview candidate.passport_copy.url %}
                    <a href="#" class="delete-file-link"
                       data-url="{% url 'candidates:delete_passport_copy' candidate.id %}"
                       data-file-name="Passport Copy">
                        <i class="fa fa-trash"></i> delete
                    </a>

                {% else %}
                    {{ form.passport_copy|as_crispy_field }}
                {% endif %}
            </div>
        </div>
        <!--'is_open_to_work', 'personal_image', 'resume_copy' -->
              <h5 class="mb-3">Job information</h5>
        <hr>
        <div class="row mb-3">

            <div class="col-md-4">
                {{ form.is_open_to_work|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {% if candidate.personal_image and candidate.personal_image.url %}
                    <strong class="mb-3">Personal Image</strong>
                    {% document_preview candidate.personal_image.url %}
                    <a href="#" class="delete-file-link"
                       data-url="{% url 'candidates:delete_personal_image' candidate.id %}"
                       data-file-name="Personal Image">
                        <i class="fa fa-trash"></i> delete
                    </a>

                {% else %}
                    {{ form.personal_image|as_crispy_field }}
                {% endif %}

            </div>
            <div class="col-md-4">
                {% if candidate.resume_copy and candidate.resume_copy.url %}
                    <strong class="mb-3">Resume Copy</strong>
                    {% document_preview candidate.resume_copy.url %}
                    <a href="#" class="delete-file-link" data-url="{% url 'candidates:delete_resume' candidate.id %}"
                       data-file-name="Resume Copy">
                        <i class="fa fa-trash"></i> delete
                    </a>

                {% else %}
                    {{ form.resume_copy|as_crispy_field }}
                {% endif %}
            </div>
        </div>

        <!-- Add other fields as needed -->
        <button type="submit" class="btn btn-primary">Save</button>
        {% if object.pk %}
            <a href="{% url 'candidate:profile' candidate_id=object.pk %}" class="btn btn-secondary">Cancel</a>
        {% endif %}
    </form>
{% endblock %}

candidates/templates/candidates/delete_file_confirm.html
{% extends "base.html" %}

{% block content %}
  <h2>Delete {{ file_type }}</h2>
  <p>Are you sure you want to delete this {{ file_type }} for {{ candidate.full_name }}?</p>
  
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'candidates:candidate_detail' candidate.pk %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

candidates/templates/candidates/education_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h2>Confirm Education Deletion</h2>
    <p>Are you sure you want to delete this education record for {{ candidate.full_name }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

candidates/templates/candidates/education_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %} {% load document_preview %}
{% load crispy_forms_filters %} {% load crispy_forms_tags %} {% block content %}
    <div class="container mt-5">
        <h2>{{ education.pk|yesno:"Edit Education,Add Education" }}</h2>
        <form method="post" enctype="multipart/form-data">
            {{ form.media }} {% csrf_token %}

            <!-- Education Information -->
            <h4>Education Information</h4>
            <div class="row mb-3">
                <div class="col-md-6">{{ form.institution|as_crispy_field }}</div>
                <div class="col-md-6">{{ form.degree|as_crispy_field }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-6">{{ form.field_of_study|as_crispy_field }}</div>

                <div class="col-md-6">{{ form.grade|as_crispy_field }}</div>
            </div>
            <div class="row mb-3">
                <div class="col-md-6">{{ form.start_date|as_crispy_field }}</div>
                <div class="col-md-6">{{ form.end_date|as_crispy_field }}</div>
            </div>

            <div class="row mb-3">
                <div class="col-md-6 inline">{{ form.online|as_crispy_field }}</div>
                <div class="col-md-6">{{ form.gpa|as_crispy_field }}</div>
            </div>

            <!-- Certification Upload -->
            <h4>Certification</h4>
            <div class="row mb-3">
                <div class="col-md-6">
                    {% if form.instance.certification_copy %}
                        <label>Certification Copy</label>
                        {% document_preview form.instance.certification_copy.url %}

                        <a
                                href="#"
                                class="delete-file-link"
                                data-url="{% url 'candidates:delete_education_certification' form.instance.id %}"
                                data-file-name=" {{ form.instance.degree }} certification for {{ form.instance.candidate.full_name }}"
                        >
                            <i class="fa fa-trash"></i> delete</a
                        >

                    {% else %} {{ form.certification_copy|as_crispy_field }} {% endif %}
                </div>
                <div class="col-md-6">
                    {% if form.instance.transcript_copy %}
                        <label>Transcript Copy</label>
                        {% document_preview form.instance.transcript_copy.url %}
                        <a
                                href="#"
                                class="delete-file-link"
                                data-url="{% url 'candidates:delete_education_transcript' form.instance.id %}"
                                data-file-name=" {{ form.instance.degree }} certification for {{ form.instance.candidate.full_name }}"
                        >
                            <i class="fa fa-trash"></i> delete</a
                        >                    {% else %} {{ form.transcript_copy|as_crispy_field }} {% endif %}
                </div>
            </div>

            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary">Save</button>
            <a
                    href="{% url 'candidates:candidate_detail' pk=candidate.pk %}"
                    class="btn btn-secondary"
            >Cancel</a
            >
        </form>
    </div>
{% endblock %}

candidates/templates/candidates/experience_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h2>Confirm Experience Deletion</h2>
    <p>Are you sure you want to delete this experience record for {{ candidate.full_name }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

candidates/templates/candidates/experience_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load document_preview %}
{% block content %}
<div class="container mt-5">
    <h2>{{ experience.pk|yesno:"Edit Experience,Add Experience" }}</h2>
    <form method="post" enctype="multipart/form-data">
        {{ form.media }}
        {% csrf_token %}

        <!-- Company Information -->
        <h4>Company Information</h4>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.company_name|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.company_location|as_crispy_field }}
            </div>
        </div>

        <!-- Reference Information -->
        <h4>Reference Information</h4>
        <div class="row mb-3">
            <div class="col-md-4">
                {{ form.reference_name|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.reference_job_title|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.reference_contact_info|as_crispy_field }}
            </div>
        </div>

        <!-- Job Information -->
        <h4>Job Information</h4>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.job_title|as_crispy_field }}
            </div>
            <div class="col-md-6">
                <!-- Departments Field -->
                <div class="form-group">
                    <label for="id_departments">{{ form.departments.label }}</label>
                    <select id="id_departments" name="departments" class="form-control select2" multiple="multiple">
                        {% for department in form.departments.field.queryset %}
                            <option value="{{ department.pk }}" {% if department.pk in form.departments.value %}selected{% endif %}>
                                {{ department }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>

        <!-- Date Information -->
        <h4>Date Information</h4>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.start_date|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.end_date|as_crispy_field }}
            </div>
        </div>

        <!-- Additional Information -->
        <h4>Additional Information</h4>
        <div class="mb-3">
            {{ form.job_responsibilities|as_crispy_field }}
        </div>

        <div class="mb-3">
            <label for="id_certification_copy">Certification Copy</label>
            {% if form.instance.certification_copy %}
                {% document_preview form.instance.certification_copy.url %}
                <a href="{% url 'candidates:delete_experience_certification' form.instance.pk  %}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Delete</a>
            {% else %}
                {{ form.certification_copy|as_crispy_field }}
            {% endif %}
        </div>

        <!-- Submit Button -->
        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function() {
        // Initialize Select2 on the departments field
        $("#id_departments").select2({
            width: '100%'  // Ensures that Select2 dropdown takes the full width of the form field
        });
    });
</script>
{% endblock %}

candidates/templates/candidates/language_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h2>Confirm language Deletion</h2>
    <p>Are you sure you want to delete this experience record for {{ candidate.full_name }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

candidates/templates/candidates/license_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}
{% load document_preview %}
{% block content %}
    <div class="container mt-5">
        <h2>{{ object.pk|yesno:"Edit License,Add License" }}</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- License Information -->
            <h4>License Information</h4>
            <div class="row mb-3">
                <div class="col-md-4">
                    {{ form.license_name|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.license_number|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.license_provider|as_crispy_field }}
                </div>

            </div>

            <!-- Date Information -->
            <h4>Date Information</h4>
            <div class="row mb-3">
                <div class="col-md-6">
                    {{ form.issued_date|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.expiry_date|as_crispy_field }}
                </div>
            </div>

            <!-- License Copy -->
            <h4>License Copy</h4>
            <div class="mb-3">
                {% if  form.instance.license_copy %}
                    <label for="id_license_copy">Certification Copy</label>
                    {% document_preview form.instance.license_copy.url %}
                    <a
                            href="#"
                            class="delete-file-link"
                            data-url="{% url 'candidates:delete_license_copy' form.instance.pk %}"
                            data-file-name=" {{ form.instance.degree }} certification for {{ form.instance.candidate.full_name }}"
                    >
                        <i class="fa fa-trash"></i> delete</a
                    >
                {% else %}
                    {{ form.license_copy|as_crispy_field }}
                {% endif %}
            </div>


            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

candidates/templates/candidates/trainingcourse_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h2>Confirm Training Course Deletion</h2>
    <p>Are you sure you want to delete this training course for {{ candidate.full_name }}?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}