DjangoConsulting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('main.urls')),
                  path('accounts/', include('accounts.urls')),
                  path("ckeditor5/", include('django_ckeditor_5.urls')),

                  path("candidates/", include("candidates.urls", namespace="candidates")),
                  path('documents/', include('manage_documents.urls')),
                  path('jobs/', include('jobs.urls', namespace='jobs')),

              ]

candidates/urls.py
# candidates/urls.py
from django.urls import path
from . import views


app_name = "candidates"

urlpatterns = [
    # Candidate URLs

    path("search/", views.candidate_search_view, name="candidate_search"),

    path("", views.candidate_list, name="candidate_list"),
    path("create/", views.candidate_create, name="candidate_create"),
    path("<int:pk>/", views.candidate_detail, name="candidate_detail"),
    path("<int:pk>/update/", views.candidate_update, name="candidate_update"),
    path("<int:pk>/delete/", views.candidate_delete, name="candidate_delete"),
    # File Deletion URLs
    path(
        "<int:candidate_pk>/delete_resume/", views.delete_resume, name="delete_resume"
    ),
    path(
        "<int:candidate_pk>/delete_personal_image/",
        views.delete_personal_image,
        name="delete_personal_image",
    ),
    path(
        "<int:candidate_pk>/delete_id_copy/",
        views.delete_id_copy,
        name="delete_id_copy",
    ),
    path(
        "<int:candidate_pk>/delete_passport_copy/",
        views.delete_passport_copy,
        name="delete_passport_copy",
    ),
    # Education URLs
    path(
        "<int:candidate_pk>/educations/create/",
        views.education_create,
        name="education_create",
    ),
    path(
        "educations/<int:pk>/update/", views.education_update, name="education_update"
    ),
    path(
        "educations/<int:pk>/delete/", views.education_delete, name="education_delete"
    ),
    # Education File Deletion
    path(
        "educations/<int:education_pk>/delete_certification/",
        views.delete_education_certification,
        name="delete_education_certification",
    ),
    path(
        "educations/<int:education_pk>/delete_transcript/",
        views.delete_education_transcript,
        name="delete_education_transcript",
    ),
    # Experience URLs
    path(
        "<int:candidate_pk>/experiences/create/",
        views.experience_create,
        name="experience_create",
    ),
    path(
        "experiences/<int:pk>/update/",
        views.experience_update,
        name="experience_update",
    ),
    path(
        "experiences/<int:pk>/delete/",
        views.experience_delete,
        name="experience_delete",
    ),
    # Experience File Deletion
    path(
        "experiences/<int:experience_pk>/delete_certification/",
        views.delete_experience_certification,
        name="delete_experience_certification",
    ),
    # Language URLs
    path(
        "languages/<int:candidate_pk>/languages/create/",
        views.language_create,
        name="language_create",
    ),
    path("languages/<int:pk>/delete/", views.language_delete, name="language_delete"),
    # Training Course URLs
    path(
        "<int:candidate_pk>/training_courses/create/",
        views.training_course_create,
        name="training_course_create",
    ),
    path(
        "training_courses/<int:pk>/update/",
        views.training_course_update,
        name="training_course_update",
    ),
    path(
        "training_courses/<int:pk>/delete/",
        views.training_course_delete,
        name="training_course_delete",
    ),
    # Training Course File Deletion
    path(
        "<int:training_course_pk>/delete_certification/",
        views.delete_training_course_certification,
        name="delete_training_course_certification",
    ),
    # License URLs
    path(
        "<int:candidate_pk>/licenses/create/",
        views.license_create,
        name="license_create",
    ),
    path("licenses/<int:pk>/update/", views.license_update, name="license_update"),
    path("licenses/<int:pk>/delete/", views.license_delete, name="license_delete"),
    # License File Deletion
    path(
        "<int:license_pk>/delete_license_copy/",
        views.delete_license_copy,
        name="delete_license_copy",
    ),
    # Candidate Application Data URLs
    path(
        "<int:candidate_pk>/application_data/update/",
        views.candidate_application_data_update,
        name="candidate_application_data_update",
    ),
    path(
        "<int:candidate_pk>/application_data/detail/",
        views.candidate_application_data_detail,
        name="candidate_application_data_detail",
    ),
    path(
        "candidate/<int:candidate_id>/delete_blood_test_report/",
        views.delete_blood_test_report,
        name="delete_blood_test_report",
    ),
    path(
        "candidate/<int:candidate_id>/delete_xray_test_report/",
        views.delete_xray_test_report,
        name="delete_xray_test_report",
    ),
    path(
        "candidate/<int:candidate_id>/delete_fit_to_work_report/",
        views.delete_fit_to_work_report,
        name="delete_fit_to_work_report",
    ),
    # DataFlow_certificate_copy
    path(
        "candidate/<int:candidate_id>/delete_dataflow_certificate/",
        views.delete_dataflow_certificate,
        name="delete_dataflow_certificate_copy",
    ),
    path(
        "candidate/<int:candidate_id>/delete_pregnancy_report/",
        views.delete_pregnancy_report,
        name="delete_pregnancy_report",
    ),
    path(
        "candidate/<int:candidate_id>/delete_dhp_certificate/",
        views.delete_dhp_certificate,
        name="delete_dhp_certificate",
    ),
    path(
        "candidate/<int:candidate_id>/delete_prometric_certificate/",
        views.delete_prometric_certificate,
        name="delete_prometric_certificate",
    ),
# delete_prometric_appointment
    path(
        "candidate/<int:candidate_id>/delete_prometric_appointment_copy/",
        views.delete_prometric_appointment_copy,
        name="delete_prometric_appointment_copy",
    ),
    # delete_police_clearance_copy
    path(
        "candidate/<int:candidate_id>/delete_police_clearance_copy/",
        views.delete_police_clearance_copy,
        name="delete_police_clearance_copy",
    ),
    # delete_visa_copy
    path(
        "candidate/<int:candidate_id>/delete_visa_copy/",
        views.delete_visa_copy,
        name="delete_visa_copy",
    ),
    path(

        "candidate/<int:candidate_id>/delete_police_clearance_copy/",
        views.delete_police_clearance_copy,
        name="delete_police_clearance_copy",
    ),
    path(
        "candidate/<int:candidate_id>/delete_visa_copy/",
        views.delete_visa_copy,
        name="delete_visa_copy",
    ),

    path('download/', views.download_file, name='download_file'),

    path('download-directory/<int:candidate_id>/', views.download_candidate_directory,
         name='download_candidate_directory'),
    path('download-vcf/<int:candidate_id>/', views.download_vcf, name='download_vcf'),

]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.job_opportunity_list, name='job_opportunity_list'),
    path('job-opportunities/', views.job_opportunity_list, name='job_opportunity_list'),
    path('job-opportunities/add/', views.job_opportunity_create, name='job_opportunity_create'),
    path('job-opportunities/<int:pk>/', views.job_opportunity_detail, name='job_opportunity_detail'),
    path('job-opportunities/<int:pk>/edit/', views.job_opportunity_edit, name='job_opportunity_edit'),
    path('job-opportunities/<int:pk>/candidates/', views.job_opportunity_candidates, name='job_opportunity_candidates'),
    # This endpoint is not used in the provided code. If you want to include it, you can uncomment it and modify the view function accordingly.
    path('job-opportunities/<int:pk>/compatible-candidates/', views.job_opportunity_compatible_candidates, name='job_opportunity_compatible_candidates'),
    path('job-opportunities/<int:job_id>/add-candidate/<int:candidate_id>/', views.job_opportunity_add_candidate, name='job_opportunity_add_candidate'),
    path('job-opportunities/<int:job_id>/remove-candidate/<int:candidate_id>/', views.job_opportunity_remove_candidate, name='job_opportunity_remove_candidate'),
]

jobs/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from simple_history.models import HistoricalRecords

from utilities.models import (
    Nationality,
    DegreeChoices,
    FieldOfStudy,
    Department,
)

from candidates.models import Candidate

class JobOpportunity(models.Model):
    job_title = models.CharField(max_length=255, verbose_name=_("Job Title"))
    job_description = models.TextField(verbose_name=_("Job Description"))
    job_department = models.ForeignKey(
        Department,
        on_delete=models.PROTECT,
        verbose_name=_("Job Department"),
        related_name='job_opportunities_as_department',  # Added related_name
    )
    company_name = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text=_("Enter the name of the company."),
        verbose_name=_("Company Name"),
    )
    minimum_years_of_experience = models.PositiveIntegerField(
        verbose_name=_("Minimum Years of Experience")
    )
    accepted_degrees = models.ManyToManyField(
        DegreeChoices,
        verbose_name=_("Accepted Degrees"),
    )
    fields_of_study = models.ManyToManyField(
        FieldOfStudy,
        verbose_name=_("Fields of Study"),
    )
    nationalities = models.ManyToManyField(
        Nationality,
        verbose_name=_("Nationalities"),
    )
    minimum_age = models.PositiveIntegerField(verbose_name=_("Minimum Age"))
    maximum_age = models.PositiveIntegerField(verbose_name=_("Maximum Age"))
    gender = models.CharField(
        choices=[("M", _("Male")), ("F", _("Female")), ("Any", _("Any"))],
        max_length=3,
        verbose_name=_("Gender"),
    )
    departments = models.ManyToManyField(
        Department,
        verbose_name=_("Required Experience Departments"),
        help_text=_("Select departments that the candidate should have experience in."),
        related_name='job_opportunities_as_required',  # Added related_name
    )
    candidates = models.ManyToManyField(
        Candidate,
        related_name='job_opportunities',
        blank=True,
        verbose_name=_("Candidates"),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    class Meta:
        verbose_name = _("Job Opportunity")
        verbose_name_plural = _("Job Opportunities")
        ordering = ["-created_at"]

    def __str__(self):
        return self.job_title

jobs/views.py
from datetime import date

from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404

from candidates.models import Candidate
from .forms import JobOpportunityForm
from .models import JobOpportunity


def job_opportunity_list(request):
    # Fetch all job opportunities
    job_opportunities = JobOpportunity.objects.all()

    # Sorting logic
    sort_by = request.GET.get("sort", "created_at")  # Default sort by created_at
    order = request.GET.get("order", "asc")  # Default order is ascending
    order_prefix = "" if order == "asc" else "-"
    job_opportunities = job_opportunities.order_by(f"{order_prefix}{sort_by}")

    # Pagination logic
    per_page = int(request.GET.get("per_page", 10))  # Default 10 items per page
    paginator = Paginator(job_opportunities, per_page)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "job_opportunities": page_obj,
        "sort_by": sort_by,
        "order": order,
        "per_page": per_page,
    }
    return render(request, 'jobs/job_opportunity_list.html', context)

@login_required
def job_opportunity_create(request):
    if request.method == 'POST':
        form = JobOpportunityForm(request.POST)
        if form.is_valid():
            job_opportunity = form.save()
            messages.success(request, 'Job Opportunity created successfully.')
            return redirect('jobs:job_opportunity_detail', pk=job_opportunity.pk)
    else:
        form = JobOpportunityForm()
    return render(request, 'jobs/job_opportunity_form.html', {'form': form})

@login_required
def job_opportunity_detail(request, pk):
    job_opportunity = get_object_or_404(JobOpportunity, pk=pk)
    assigned_candidates = job_opportunity.candidates.all()
    return render(request, 'jobs/job_opportunity_detail.html', {
        'job_opportunity': job_opportunity,
        'assigned_candidates': assigned_candidates,
    })

@login_required
def job_opportunity_edit(request, pk):
    job_opportunity = get_object_or_404(JobOpportunity, pk=pk)
    if request.method == 'POST':
        form = JobOpportunityForm(request.POST, instance=job_opportunity)
        if form.is_valid():
            job_opportunity = form.save()
            messages.success(request, 'Job Opportunity updated successfully.')
            return redirect('jobs:job_opportunity_detail', pk=job_opportunity.pk)
    else:
        form = JobOpportunityForm(instance=job_opportunity)
    return render(request, 'jobs/job_opportunity_form.html', {'form': form})



@login_required
def job_opportunity_compatible_candidates(request, pk):
    job_opportunity = get_object_or_404(JobOpportunity, pk=pk)

    # Exclude candidates already associated with any job opportunity
    candidates = Candidate.objects.filter(job_opportunities__isnull=True)

    # Filter based on gender
    if job_opportunity.gender != 'Any':
        candidates = candidates.filter(gender=job_opportunity.gender)

    # Filter based on age
    today = date.today()
    min_birth_date = today - relativedelta(years=job_opportunity.maximum_age)
    max_birth_date = today - relativedelta(years=job_opportunity.minimum_age)
    candidates = candidates.filter(birthday__range=(min_birth_date, max_birth_date))

    # Filter based on nationality
    candidates = candidates.filter(nationality__in=job_opportunity.nationalities.all())

    # Filter based on accepted degrees and fields of study
    candidates = candidates.filter(
        educations__degree__in=job_opportunity.accepted_degrees.all(),
        educations__field_of_study__in=job_opportunity.fields_of_study.all()
    ).distinct()

    # Filter based on minimum years of experience
    compatible_candidates = [
        candidate for candidate in candidates if candidate.get_total_experience_years() >= job_opportunity.minimum_years_of_experience
    ]

    # Sorting logic
    sort_by = request.GET.get("sort", "full_name")
    order = request.GET.get("order", "asc")
    reverse_order = order == "desc"

    if sort_by == "full_name":
        compatible_candidates.sort(key=lambda x: x.full_name.lower(), reverse=reverse_order)
    elif sort_by == "email":
        compatible_candidates.sort(key=lambda x: x.email.lower(), reverse=reverse_order)
    elif sort_by == "total_experience":
        compatible_candidates.sort(key=lambda x: x.get_total_experience_years(), reverse=reverse_order)
    elif sort_by == "age":
        compatible_candidates.sort(key=lambda x: x.age_in_years or 0, reverse=reverse_order)

    # Pagination logic
    per_page = int(request.GET.get("per_page", 10))  # Default 10 items per page
    paginator = Paginator(compatible_candidates, per_page)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "job_opportunity": job_opportunity,
        "candidates": page_obj,
        "sort_by": sort_by,
        "order": order,
        "per_page": per_page,
    }
    return render(request, 'jobs/job_opportunity_compatible_candidates.html', context)


@login_required
def job_opportunity_add_candidate(request, job_id, candidate_id):
    job_opportunity = get_object_or_404(JobOpportunity, pk=job_id)
    candidate = get_object_or_404(Candidate, pk=candidate_id)
    # Ensure candidate is not already associated with a job opportunity
    if candidate.job_opportunities.exists():
        messages.error(request, 'Candidate is already assigned to a job opportunity.')
    else:
        job_opportunity.candidates.add(candidate)
        messages.success(request, f'Candidate {candidate.full_name} added to job opportunity.')
    return redirect('jobs:job_opportunity_compatible_candidates', pk=job_opportunity.pk)


def job_opportunity_remove_candidate(request, job_id, candidate_id):
    job_opportunity = get_object_or_404(JobOpportunity, pk=job_id)

    candidate = get_object_or_404(Candidate, pk=candidate_id)
    if candidate.job_opportunities.exists():
        print("Job with candidate", job_opportunity)
        job_opportunity.candidates.remove(candidate)
        messages.success(request, f'Candidate {candidate.full_name} removed from job opportunity.')
    else:
        messages.error(request, 'Candidate is not assigned to this job opportunity.')
    return redirect('jobs:job_opportunity_detail', pk =job_opportunity.pk)


def job_opportunity_candidates(request, pk):
    job_opportunity = get_object_or_404(JobOpportunity, pk=pk)
    candidates = job_opportunity.candidates.all()
    return render(request, 'jobs/job_opportunity_candidates.html', {'job_opportunity': job_opportunity, 'candidates': candidates})

jobs/templates/jobs/job_opportunity_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}


    <!-- Action Buttons -->
    <div class="row mt-3">
        <div class="col">
            <a href="{% url 'jobs:job_opportunity_compatible_candidates' job_opportunity.pk %}" class="btn btn-success">
                <i class="fas fa-search"></i> {% trans "View Compatible Candidates" %}
            </a>
            <a href="{% url 'jobs:job_opportunity_list' %}" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> {% trans "Back to Job Opportunities" %}
            </a>
        </div>
    </div>
    <div class="container mt-4">
        <!-- Job Opportunity Header -->
        <div class="row mb-4">
            <div class="col">
                <h1><i class="fas fa-briefcase"></i> {{ job_opportunity.job_title }}</h1>
            </div>
        </div>

        <!-- Job Opportunity Details -->
        <div class="row">
            <!-- Left Column -->
            <div class="col-md-6">
                <p><strong><i
                        class="fas fa-building"></i> {% trans "Company Name" %}:</strong> {{ job_opportunity.company_name }}
                </p>
                <p><strong><i
                        class="fas fa-sitemap"></i> {% trans "Department" %}:</strong> {{ job_opportunity.job_department }}
                </p>
                <p><strong><i
                        class="fas fa-user-clock"></i> {% trans "Minimum Years of Experience" %}:</strong> {{ job_opportunity.minimum_years_of_experience }}
                </p>
                <p><strong><i
                        class="fas fa-user"></i> {% trans "Gender" %}:</strong> {{ job_opportunity.get_gender_display }}
                </p>
                <p><strong><i
                        class="fas fa-birthday-cake"></i> {% trans "Minimum Age" %}:</strong> {{ job_opportunity.minimum_age }}
                </p>
                <p><strong><i
                        class="fas fa-birthday-cake"></i> {% trans "Maximum Age" %}:</strong> {{ job_opportunity.maximum_age }}
                </p>
            </div>

            <!-- Right Column -->
            <div class="col-md-6">
                <p><strong><i class="fas fa-layer-group"></i> {% trans "Required Experience Departments" %}:</strong>
                    {% for dept in job_opportunity.departments.all %}
                        {{ dept }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p><strong><i class="fas fa-graduation-cap"></i> {% trans "Accepted Degrees" %}:</strong>
                    {% for degree in job_opportunity.accepted_degrees.all %}
                        {{ degree.degree }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p><strong><i class="fas fa-book"></i> {% trans "Fields of Study" %}:</strong>
                    {% for field in job_opportunity.fields_of_study.all %}
                        {{ field }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
                <p><strong><i class="fas fa-flag"></i> {% trans "Nationalities" %}:</strong>
                    {% for nationality in job_opportunity.nationalities.all %}
                        {{ nationality }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            </div>
        </div>

        <!-- Job Description -->
        <div class="row mt-4">
            <div class="col">
                <h4><i class="fas fa-file-alt"></i> {% trans "Job Description" %}</h4>
                <div class="border p-3">
                    {{ job_opportunity.job_description|linebreaks }}
                </div>
            </div>
        </div>

        <!-- Assigned Candidates -->
        <div class="row mt-5">
            <div class="col">
                <h3><i class="fas fa-users"></i> {% trans "Assigned Candidates" %}</h3>
                {% if assigned_candidates %}
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>{% trans "Full Name" %}</th>
                            <th>{% trans "Email" %}</th>
                            <th>{% trans "Phone Number" %}</th>
                            <th>{% trans "WhatsApp Number" %}</th>
                            <th>{% trans "Actions" %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for candidate in assigned_candidates %}
                            <tr>
                                <td>
                                    <a href="{% url 'candidates:candidate_detail' pk=candidate.pk %}">
                                        {{ candidate.full_name }}
                                    </a>
                                </td>
                                <td>
                                    {% if candidate.email %}
                                        <a href="mailto:{{ candidate.email }}" class="text-decoration-none">
                                            {{ candidate.email}}
                                        </a>
                                    {% endif %}
                                </td>


                             <td>{% if candidate.call_phone_number %}
                                <i class="fa fa-phone" aria-hidden="true"></i>
                                <a href="tel:{{ candidate.call_phone_number }}"
                                   class="btn btn-link">{{ candidate.call_phone_number }}</a>
                            {% endif %}

                            </td>
                            <td>
                                {% if candidate.whatsapp_number %}
                                    <i class="fab fa-whatsapp"></i>
                                    <a href="https://wa.me/{{ candidate.whatsapp_number }}" target="_blank"
                                       class="btn btn-link">
                                        {{ candidate.whatsapp_number }}
                                    </a>
                                {% else %}
                                    <i class="fab fa-whatsapp"></i>
                                    <a href="https://wa.me/{{ candidate.call_phone_number }}" target="_blank"
                                       class="btn btn-link">
                                        {{ candidate.call_phone_number }}
                                    </a>
                                {% endif %}


                            </td>
                                <td>
                                    <a href="" class="btn btn-danger btn-sm"
                                       data-url="{% url 'jobs:job_opportunity_remove_candidate' job_opportunity.pk candidate.pk %}"
                                       data-file-name="  {{ candidate.full_name }}">
                                        <i class="fas fa-trash-alt"></i>
                                        {% trans "Remove" %}
                                    </a>

                                    <a href="{% url 'candidates:candidate_application_data_update' candidate.pk %}"
                                       class="btn btn-primary btn-sm">
                                        <i class="fas fa-file-signature"></i> {% trans "Application" %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>{% trans "No candidates assigned to this job opportunity." %}</p>
                {% endif %}
            </div>
        </div>

    </div>
{% endblock %}

jobs/templates/jobs/job_opportunity_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
<div class="container mt-4">
    {% if form.instance.pk %}
        <h1>{% trans "Edit Job Opportunity" %}</h1>
    {% else %}
        <h1>{% trans "Create Job Opportunity" %}</h1>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}

        <!-- Job Details Section -->
        <h5 class="mb-3">{% trans "Job Details" %}</h5>
        <hr>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.job_title|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.company_name|as_crispy_field }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.job_department|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.departments|as_crispy_field }}
            </div>
        </div>

        <div class="mb-3">
            {{ form.job_description|as_crispy_field }}
        </div>

        <!-- Requirements Section -->
        <h5 class="mb-3">{% trans "Candidate Requirements" %}</h5>
        <hr>
        <div class="row mb-3">
            <div class="col-md-4">
                {{ form.minimum_years_of_experience|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.minimum_age|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.maximum_age|as_crispy_field }}
            </div>
        </div>

        <div class="mb-3">
            {{ form.gender|as_crispy_field }}
        </div>

        <!-- Accepted Degrees and Fields of Study -->
        <h5 class="mb-3">{% trans "Educational Requirements" %}</h5>
        <hr>
        <div class="mb-3">
            {{ form.accepted_degrees|as_crispy_field }}
        </div>
        <div class="mb-3">
            {{ form.fields_of_study|as_crispy_field }}
        </div>

        <!-- Nationalities -->
        <h5 class="mb-3">{% trans "Preferred Nationalities" %}</h5>
        <hr>
        <div class="mb-3">
            {{ form.nationalities|as_crispy_field }}
        </div>

        <!-- Submit Button -->
        <button type="submit" class="btn btn-success">{% trans "Save" %}</button>
        <a href="{% url 'jobs:job_opportunity_list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
    </form>
</div>
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function() {
        // Initialize Select2 on the departments field
        $("#id_accepted_degrees").select2({
            width: '100%'  // Ensures that Select2 dropdown takes the full width of the form field
        }); 
        $("#id_nationalities").select2({
            width: '100%'  // Ensures that Select2 dropdown takes the full width of the form field
        });
        $("#id_departments").select2({
            width: '100%'  // Ensures that Select2 dropdown takes the full width of the form field
        });    
        $("#id_fields_of_study").select2({
            width: '100%'  // Ensures that Select2 dropdown takes the full width of the form field
        });
    });
</script>
{% endblock %}